version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - llmnet
    volumes:
      - ./frontend:/app  # Dev-friendly: hot reload
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

  backend:
    build:
      context: ./backend
    working_dir: /app
    ports:
      - "5000:5000"
    networks:
      - llmnet
    volumes:
      - ./backend:/app  # Dev-friendly: hot reload
    command: uvicorn main:app --host 0.0.0.0 --port 5000

networks:
  llmnet:
    driver: bridge
