version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - llmnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - llmnet

networks:
  llmnet:
    driver: bridge
